language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  ## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy

  ## Tagging
  - docker tag udagram-api-feed quangdang2001/udagram-api-feed:v10
  - docker tag udagram-frontend quangdang2001/udagram-frontend:v10
  - docker tag udagram-api-user quangdang2001/udagram-api-user:v10
  - docker tag reverseproxy quangdang2001/reverseproxy:v10

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quangdang2001/udagram-api-feed:v10
  - docker push quangdang2001/udagram-frontend:v10
  - docker push quangdang2001/udagram-api-user:v10
  - docker push quangdang2001/reverseproxy:v10
