apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: quangdang2001/udagram-api-feed:v5
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 800m
            requests:
              cpu: 500m
