apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - name: backend-user
          image: quangdang2001/udagram-api-user:v7
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 250m
