apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: quangdang2001/udagram-reverseproxy:v7
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 250m
